[phases.setup]
nixPkgs = ['nodejs_20', 'python3']

[phases.install]
cmds = [
  'npm ci --prefix frontend --legacy-peer-deps',
  'npm ci --prefix backend'
]

[phases.build]
cmds = [
  'npm run build --prefix frontend'
]

[start]
cmd = 'cd backend && NODE_ENV=production node src/server.js'
